#!/bin/bash

usage() {
    echo "Usage: $0 [--mount|--unmount] [--label LABEL_PREFIX] [--read-only] [--mount-point MOUNT_POINT]"
    echo "Example: $0 --mount --label 'CHIA'"
    exit 1
}

if [ "$#" -lt 1 ]; then
    usage
fi

action=""
label_prefix="CHIA"
read_only=""
mount_point=""

while [ "$#" -gt 0 ]; do
    case "$1" in
        --mount)
            action="mount"
            shift
            ;;
        --unmount)
            action="unmount"
            shift
            ;;
        --label)
            label_prefix="$2"
            shift 2
            ;;
        --read-only)
            read_only="yes"
            shift
            ;;
        --mount-point)
            mount_point="$2"
            shift 2
            ;;
        *)
            echo "Unknown argument: $1"
            usage
            ;;
    esac
done

if [ -z "$action" ]; then
    echo "Please specify an action: --mount or --unmount"
    usage
fi

label_pattern="${label_prefix}*"
found_disks=0
username=$(whoami)

if [ -z "$mount_point" ]; then
    mount_point="/media/$username"
fi

mounted_devices=()

if [ "$action" == "mount" ]; then
    mount_options="rw,noatime"
    if [ "$read_only" == "yes" ]; then
        mount_options="ro,noatime"
    fi

    while IFS= read -r disk; do
        device=$(readlink -f "$disk")
        disk_mount_point="$mount_point/$(basename "$disk")"
        mkdir -p "$disk_mount_point"
        mount -v -o "$mount_options" "$device" "$disk_mount_point" && mounted_devices+=("$device")
        found_disks=1
    done < <(find /dev/disk/by-label -name "$label_pattern")
elif [ "$action" == "unmount" ]; then
    while IFS= read -r disk; do
        device=$(readlink -f "$disk")
        mount_info=$(findmnt -n -o SOURCE,TARGET "$device")
        if [ -n "$mount_info" ]; then
            read -r mounted_device mounted_path <<<"$mount_info"
            umount -v "$mounted_device"
             found_disks=1
        fi
    done < <(find /dev/disk/by-label -name "$label_pattern")
else
    echo "Invalid action: '$action'. Use '--mount' or '--unmount'."
    exit 1
fi

if [ "$found_disks" -eq 0 ]; then
    echo "No disks found with the label pattern: $label_pattern"
fi

if [ "$action" == "mount" ] && [ ${#mounted_devices[@]} -gt 0 ]; then
    echo
    echo "# Add these entries to /etc/fstab to make mounting of your CHIA drives persistant"
    echo "or (better!) use the systemd services provided in the chiagarden repository"
    echo ""
    for device in "${mounted_devices[@]}"; do
        uuid=$(blkid -s UUID -o value "$device")
        mount_info=$(findmnt -n -o TARGET,OPTIONS "$device")
        if [ -n "$mount_info" ]; then
            read -r mounted_path mounted_options <<<"$mount_info"
            fstype=$(blkid -s TYPE -o value "$device")
            echo "UUID=$uuid $mounted_path $fstype $mounted_options 0 0"
        fi
    done
    echo ""
fi
